### ISSUE TITLE
Compile errors with v1.0.3.3

### ISSUE THREAD

**Issue by sjakobi** [snapframework/snap-server#110]
Now that `blaze-builder-0.4.1.0` is out, I get a compile error with `snap-server-1.0.3.3`:

```
src/Snap/Internal/Http/Server/Config.hs:289:10: error:
    • No instance for (Semigroup (Config m a))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Config m a)’
    |
289 | instance Monoid (Config m a) where
    |          ^^^^^^^^^^^^^^^^^^^
```

Maybe consider revising some releases with lower bounds on base or deprecating them.

**Comment by mightybyte** [comment]
I added an upper bound on base.  Let me know if that doesn't stop the compile error.

**Comment by sjakobi** [comment]
Oh well, cabal's solver picked v1.0.3.2 now! :) I guess you'll have to release a new version… :)

**Comment by 23Skidoo** [comment]
1.0.3.0 has the same problem.

**Comment by 23Skidoo** [comment]
`master` works fine with GHC 8.4.1, so it looks like this will be fixed once the new release is out. When can we expect to see it?

**Comment by sjakobi** [comment]
> master works fine with GHC 8.4.1, so it looks like this will be fixed once the new release is out. When can we expect to see it?

@23Skidoo: I had just asked the same question. [In the next few days](https://github.com/snapframework/snap-server/pull/111#issuecomment-374397497) was the answer.

**Comment by 23Skidoo** [comment]
Great, thanks!

**Comment by mightybyte** [comment]
Just uploaded to hackage
